name: sky_clean_weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  geolocator: ^8.2.0


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - images/



  fonts:
    - family: SyneMono
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
    - family: SyneMonoRegular
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
